### ISSUE TITLE
Re: iomem=relaxed Should 'GRUB_CMDLINE_LINE' be 'GRUB_CMDLINE_LINUX'?

### ISSUE THREAD

**Issue by briancady413** [JaGoLi/corevantage#1]
There's no documentation of GRUB_CMDLINE_LINE that I found.
"IMPORTANT: To be able to run this application, the kernel parameter iomem=relaxed must be included in the bootloader configuration.
For grub, it must be in the GRUB_CMDLINE_LINE parameter of the file /etc/default/grub"

**Comment by JaGoLi** [comment]
I made a small mistake. It should be GRUB_CMDLINE_LINUX
